@name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example2.mp3"
Content-Type: audio/mpeg

< ./example2.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/c1b60cb0-40af-474d-a064-446a3f2d80bd/transcription
Content-Type: application/json

{
  "prompt": "especies"
}

###

# @name generate-transcription

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "c1b60cb0-40af-474d-a064-446a3f2d80bd",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''"
}